area search: validate optional fields only if active
City-of-Helsinki/mvj-ui-public pull request #115
Opened 2024-03-05 11:06 UTC by NC-jsAhonen

There are sections on the area search application form that can be set to active or inactive. When they are inactive, they are invisible and should not be included in the form validations. These changes implement that.

Attention: There is also a need to create conditional validations for the backend as well in order for the whole functionality to work properly.

2024-03-07 08:58 UTC, henrinie-nc commented on src/application/validations.ts
> +        if (optionalFieldsCheckbox) {
What is the purpose of this if?

2024-03-07 09:13 UTC, henrinie-nc commented on src/application/validations.ts
> +      let sectionFields = section.fields;
Could be const?

2024-03-07 09:13 UTC, henrinie-nc commented on src/application/validations.ts
> +      let optionalFieldsCheckbox: ApplicationField | undefined;
I would recommend putting this piece of logic in a function, and then name the function so that it is apparent what is being done

2024-03-12 07:22 UTC, NC-jsAhonen commented
I separated the checking logic to a separate function, and added some clarifying comments.

2024-03-13 08:14 UTC, henrinie-nc commented on src/application/helpers.ts
> +): boolean | undefined => {
The function name indicates a true of false response, undefined migth not be expected. So it would make sense that this doesn't return undefined

2024-03-13 08:18 UTC, henrinie-nc commented on src/application/helpers.ts
> +): boolean | undefined => {
Looking at the function overall, it seems a bit messy. For instance `optionalFieldsCheckbox` can be a field or undefined, yet it is cast later as a string. The purpose seems a bit lost to me.

2024-03-13 08:18 UTC, henrinie-nc commented on src/application/validations.ts
> +      const optionalFieldsActive: boolean | undefined = isOptionalFieldsActive(
It sounds very much like this should be a boolean and not undefined

2024-03-13 08:20 UTC, henrinie-nc requested changes
`isOptionalFieldsActive` implementation should be improved, for something that is named `is...`, returning `undefined` does not make sense if it is not necessary.

2024-03-20 11:25 UTC, NC-jsAhonen commented
I renamed the function to hideOptionalFields, and simplified the function's logic to only booleans.

2024-03-21 07:06 UTC, NC-jsAhonen commented
I replaced the string access pattern with an if else statement to make it more readable. It essentially does the same as the previous one but it tells the underlying logic more explicitly.

2024-03-21 12:19 UTC, henrinie-nc approved these changes
Ok

2024-03-21 12:27 UTC, merged